name: 'Publish'
description: 'GitHub Action to publish projects and packages'
author: 'godban'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  npm_token:
    description: 'npm token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: truck
  color: blue
